[scrapyd]
bind_address= 0.0.0.0
http_port   = 6800
eggs_dir    = /scrapyd/eggs
logs_dir    = /scrapyd/logs
items_dir   = /scrapyd/items
dbs_dir     = /scrapyd/dbs

[services]
schedule.json     = scrapyd.webservice.Schedule
cancel.json       = scrapyd.webservice.Cancel
status.json       = scrapyd.webservice.Status
addversion.json   = scrapyd.webservice.AddVersion
listprojects.json = scrapyd.webservice.ListProjects
listversions.json = scrapyd.webservice.ListVersions
listspiders.json  = scrapyd.webservice.ListSpiders
delproject.json   = scrapyd.webservice.DeleteProject
delversion.json   = scrapyd.webservice.DeleteVersion
listjobs.json     = scrapyd.webservice.ListJobs
daemonstatus.json = scrapyd.webservice.DaemonStatus
